#!/usr/bin/env python3
# Generates firmware/src/logo_wine.h — an 80×80 RGB565A8 wine-glass logo for
# the jacques.de Wine-Edition build. The art is described as a 20×20 logical
# grid which is then nearest-neighbour scaled 4× to 80×80 so it shares the
# blocky pixel-art language of the splash sprites.
#
# Optional second output: with `--png <path> [--png-size N]` the same grid is
# also rendered as a high-resolution PNG (default 1024×1024) for the Tauri
# companion-app icon. Single source of truth for the wine-glass artwork.

import argparse
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT_FILE = os.path.join(HERE, "..", "firmware", "src", "logo_wine.h")

SCALE = 4              # 20 × 4 = 80
W_LOGICAL = 20
H_LOGICAL = 20
W = W_LOGICAL * SCALE
H = H_LOGICAL * SCALE

# Palette (RGB888 + alpha). Index '.' = fully transparent.
PALETTE = {
    ".": (0, 0, 0, 0),         # transparent
    "H": (255, 255, 255, 255), # rim shine (white)
    "G": (60,  60,  68,  255), # glass outline (dark cool grey)
    "g": (140, 140, 150, 255), # glass body shadow (semi-translucent feel)
    "w": (162, 64,  72,  255), # wine surface highlight (lighter bordeaux)
    "W": (122, 46,  54,  255), # wine main (bordeaux)
    "D": (60,  20,  28,  255), # wine deep shadow
    "S": (50,  50,  58,  255), # stem
    "B": (200, 200, 208, 255), # base disc (light grey)
    "b": (110, 110, 120, 255), # base shadow
}

# 20×20 logical sprite — wine glass with bordeaux wine.
ART = """
....................
......HHHHHHHH......
.....GwwwwwwwwG.....
....Gw........gG....
....Gw........gG....
....Gw........gG....
....GwwwwwwwwwwG....
....GWWWWWWWWWWG....
....GWWWWWWWWWWG....
....GWWWWWWWWWWG....
....GDWWWWWWWWdG....
.....GWWWWWWWWG.....
......GWWWWWWG......
.......GWWWWG.......
........GSSG........
.........SS.........
.........SS.........
........SbbS........
......BBBBBBBB......
.....BBBBBBBBBB.....
"""

ART = [ln for ln in ART.split("\n") if ln != ""]
assert len(ART) == H_LOGICAL, f"need {H_LOGICAL} rows, got {len(ART)}"
for r, ln in enumerate(ART):
    assert len(ln) == W_LOGICAL, f"row {r} length {len(ln)} != {W_LOGICAL}: {ln!r}"

# 'd' is a per-row alias used inside the grid; alias it to D so we don't bloat
# the palette dict when re-using shades. Replace any aliases here:
ALIASES = {"d": "D"}


def lookup(ch):
    return PALETTE[ALIASES.get(ch, ch)]


def rgb565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main():
    total = W * H
    color = bytearray(total * 2)
    alpha = bytearray(total)

    for y in range(H):
        for x in range(W):
            lx = x // SCALE
            ly = y // SCALE
            ch = ART[ly][lx]
            r, g, b, a = lookup(ch)
            c = rgb565(r, g, b)
            i = y * W + x
            color[i * 2 + 0] = c & 0xFF
            color[i * 2 + 1] = (c >> 8) & 0xFF
            alpha[i] = a

    all_bytes = bytes(color) + bytes(alpha)

    out = [
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define LOGO_WINE_WIDTH {W}",
        f"#define LOGO_WINE_HEIGHT {H}",
        f"// RGB565A8: {total} RGB565 pixels (little-endian) followed by {total} alpha bytes",
        f"// Generated by tools/build_wine_logo.py — edit ART grid there, not here.",
        f"static const uint8_t logo_wine_data[{len(all_bytes)}] = {{",
    ]
    line = "    "
    for i, byte in enumerate(all_bytes):
        line += f"0x{byte:02X}"
        if i != len(all_bytes) - 1:
            line += ", "
        if (i + 1) % 16 == 0:
            out.append(line.rstrip())
            line = "    "
    if line.strip():
        out.append(line.rstrip(", "))
    out.append("};")
    out.append("")

    out_path = os.path.abspath(OUT_FILE)
    with open(out_path, "w") as f:
        f.write("\n".join(out))
    print(f"  wrote {out_path}  ({W}×{H}, {len(all_bytes)} bytes)")


def render_png(png_path, png_size, padding_pct):
    from PIL import Image

    # Reserve a transparent margin so the icon sits nicely in the macOS dock.
    pad = int(round(png_size * padding_pct))
    inner = png_size - 2 * pad
    cell = inner // W_LOGICAL
    inner = cell * W_LOGICAL  # snap to integer cell pitch for crisp NN scaling
    origin = (png_size - inner) // 2

    img = Image.new("RGBA", (png_size, png_size), (0, 0, 0, 0))
    px = img.load()
    for ly in range(H_LOGICAL):
        for lx in range(W_LOGICAL):
            r, g, b, a = lookup(ART[ly][lx])
            if a == 0:
                continue
            x0 = origin + lx * cell
            y0 = origin + ly * cell
            for dy in range(cell):
                for dx in range(cell):
                    px[x0 + dx, y0 + dy] = (r, g, b, a)

    os.makedirs(os.path.dirname(os.path.abspath(png_path)), exist_ok=True)
    img.save(png_path, "PNG")
    print(f"  wrote {os.path.abspath(png_path)}  ({png_size}×{png_size} PNG, cell={cell}px)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Build wine-glass logo (firmware header + optional PNG).")
    parser.add_argument("--png", metavar="PATH", help="Also render the logo as PNG at PATH.")
    parser.add_argument("--png-size", type=int, default=1024, help="PNG edge length in pixels (default 1024).")
    parser.add_argument("--png-padding", type=float, default=0.08, help="Transparent margin as fraction of edge (default 0.08).")
    args = parser.parse_args()
    main()
    if args.png:
        render_png(args.png, args.png_size, args.png_padding)
