#!/usr/bin/env node
/**
 * Converts scraped JSON animation data to firmware/src/splash_animations.h.
 *
 * Each animation carries its own grid size (auto-detected from frame data —
 * the original claudepix set is 20×20; the Wine-Edition 48×48 sprites use the
 * same JSON schema with a larger grid). The palette length is also per-sprite
 * (was fixed at 10; PixelLab-generated sprites use up to 32). splash.cpp reads
 * grid + palette_size from each splash_anim_def_t at render time, so both
 * resolutions coexist in the same firmware build.
 *
 * Usage: node convert_to_c.js [--in DIR] [--out FILE]
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
const opt = (k, def) => { const i = args.indexOf(k); return i >= 0 ? args[i + 1] : def; };

const IN_DIR = path.resolve(opt('--in', path.join(__dirname, 'claudepix_data')));
const OUT_FILE = path.resolve(opt('--out',
  path.join(__dirname, '..', 'firmware', 'src', 'splash_animations.h')));

function safeIdent(s) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '');
}

function hexToRgb565(hex) {
  if (!hex || hex === 'transparent') return 0x0000;  // dark bg
  let h = hex.replace('#', '');
  if (h.length === 3) h = h.split('').map(c => c + c).join('');
  const r = parseInt(h.substr(0, 2), 16);
  const g = parseInt(h.substr(2, 2), 16);
  const b = parseInt(h.substr(4, 2), 16);
  return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3);
}

function paletteToRgb565(palette) {
  return palette.map(hexToRgb565);
}

function main() {
  if (!fs.existsSync(IN_DIR)) {
    console.error(`No scraped data at ${IN_DIR}. Run scrape_claudepix.js first.`);
    process.exit(1);
  }

  const indexPath = path.join(IN_DIR, '_index.json');
  if (!fs.existsSync(indexPath)) {
    console.error(`Missing ${indexPath}.`);
    process.exit(1);
  }

  const index = JSON.parse(fs.readFileSync(indexPath, 'utf8'));
  console.log(`Converting ${index.length} animations`);

  let out = '';
  out += '// ============================================================\n';
  out += '// Splash animations — generated by tools/convert_to_c.js.\n';
  out += '// Source: https://claudepix.vercel.app (20x20 pixel-art creature\n';
  out += '// animation library). Frames extracted by tools/scrape_claudepix.js\n';
  out += '// from per-animation HTML files served by the source site.\n';
  out += '// Do not edit by hand — re-run the scraper + converter to refresh.\n';
  out += '// ============================================================\n';
  out += '// Each animation carries its own per-sprite palette (up to 256 entries)\n';
  out += '// and grid size. The splash module reads `grid` and `palette_size`\n';
  out += '// from each entry, so 20×20 and 48×48 sets coexist in one build.\n';
  out += '#pragma once\n#include <stdint.h>\n\n';

  out += 'typedef struct {\n';
  out += '    const char *name;\n';
  out += '    const char *category;\n';
  out += '    uint16_t frame_count;\n';
  out += '    uint16_t grid;          /* sprite is grid×grid cells */\n';
  out += '    uint16_t palette_size;  /* number of valid entries in palette */\n';
  out += '    const uint16_t *palette;\n';
  out += '    const uint8_t *frames;  /* frame_count × grid × grid bytes */\n';
  out += '    const uint16_t *holds;\n';
  out += '} splash_anim_def_t;\n\n';

  const entries = [];

  for (const meta of index) {
    const ident = safeIdent(meta.filename.replace(/\.html?$/, ''));
    const dataPath = path.join(IN_DIR, meta.filename.replace(/\.html?$/, '.json'));
    const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

    // Auto-detect grid from the first frame's row count. We require square
    // grids and identical sizes across frames within one animation.
    const grid = data.frames[0].grid.length;
    for (const f of data.frames) {
      if (f.grid.length !== grid || f.grid.some(r => r.length !== grid)) {
        throw new Error(`${meta.filename}: non-square or mismatched grid (expected ${grid}×${grid})`);
      }
    }

    const palSize = data.palette.length;
    const pal565 = paletteToRgb565(data.palette);
    out += `static const uint16_t splash_${ident}_palette[${palSize}] = {`;
    out += pal565.map(c => `0x${c.toString(16).toUpperCase().padStart(4, '0')}`).join(',');
    out += '};\n';

    const cells = grid * grid;
    out += `static const uint8_t splash_${ident}_frames[${data.frames.length * cells}] = {\n`;
    for (const f of data.frames) {
      for (let r = 0; r < grid; r++) {
        out += '    ' + f.grid[r].join(',') + ',\n';
      }
    }
    out += '};\n';

    out += `static const uint16_t splash_${ident}_holds[${data.frames.length}] = {`;
    out += data.frames.map(f => f.hold).join(',');
    out += '};\n\n';

    entries.push({ ident, name: data.name, category: data.category, count: data.frames.length, grid, palSize });
  }

  out += `#define SPLASH_ANIM_COUNT ${entries.length}\n`;
  out += 'static const splash_anim_def_t splash_anims[SPLASH_ANIM_COUNT] = {\n';
  for (const e of entries) {
    out += `    {"${e.name}", "${e.category}", ${e.count}, ${e.grid}, ${e.palSize}, splash_${e.ident}_palette, splash_${e.ident}_frames, splash_${e.ident}_holds},\n`;
  }
  out += '};\n';

  fs.writeFileSync(OUT_FILE, out);
  console.log(`Wrote ${OUT_FILE} (${entries.length} animations, ${(out.length / 1024).toFixed(1)} KB)`);
}

main();
